//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amazon_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillItem
    {
        public int Id { get; set; }
        public int Menu_Id { get; set; }
        public int Bill_Id { get; set; }
        public int Price { get; set; }
    
        public virtual ListBill ListBill { get; set; }
        public virtual MenuAmazon MenuAmazon { get; set; }
    }
}
