//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amazon_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APD65_63011212019Entities : DbContext
    {
        public APD65_63011212019Entities()
            : base("name=APD65_63011212019Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BillItem> BillItems { get; set; }
        public virtual DbSet<ListBill> ListBills { get; set; }
        public virtual DbSet<MenuAmazon> MenuAmazons { get; set; }
    }
}
