//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Amezon_Cafe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project_Amezon_Cafe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap เฟรชคาเฟ่ลาเต้__Fresh_Cafe_Latte_ {
            get {
                object obj = ResourceManager.GetObject("เฟรชคาเฟ่ลาเต้ (Fresh Cafe Latte)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap เฟรชมิลค์ที__Fresh_Milk_Tea_ {
            get {
                object obj = ResourceManager.GetObject("เฟรชมิลค์ที (Fresh Milk Tea)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap เอสเพรสโซ่__Espressso_ {
            get {
                object obj = ResourceManager.GetObject("เอสเพรสโซ่ (Espressso)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap แบล็คคอฟฟี่__Black_Coffee_ {
            get {
                object obj = ResourceManager.GetObject("แบล็คคอฟฟี่ (Black Coffee)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap แบล็คคอฟฟี่น้ำผึ่้ง__Honey_Black_Coffee_ {
            get {
                object obj = ResourceManager.GetObject("แบล็คคอฟฟี่น้ำผึ่้ง (Honey Black Coffee)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap แบล็คคอฟฟี่น้ำผึ้งมะนาว__Black_Coffee_Honey_Lemon_ {
            get {
                object obj = ResourceManager.GetObject("แบล็คคอฟฟี่น้ำผึ้งมะนาว (Black Coffee Honey Lemon)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap แบล็คที่ฮันนี่__Black_Tea_Honey_ {
            get {
                object obj = ResourceManager.GetObject("แบล็คที่ฮันนี่ (Black Tea Honey)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap โยเกิร์ตสมูทตี้__มิกซ์เบอร์รี่_ {
            get {
                object obj = ResourceManager.GetObject("โยเกิร์ตสมูทตี้ (มิกซ์เบอร์รี่)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap โยเกิร์ตสมูทตี้__สตรอเบอร์รี่_ {
            get {
                object obj = ResourceManager.GetObject("โยเกิร์ตสมูทตี้ (สตรอเบอร์รี่)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ไลท์คอฟฟี่ฮันนี่__Light_Coffee_Honey_ {
            get {
                object obj = ResourceManager.GetObject("ไลท์คอฟฟี่ฮันนี่ (Light Coffee Honey)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ไวท์_ช็อค_มัคคิอาโต้ {
            get {
                object obj = ResourceManager.GetObject("ไวท์ ช็อค มัคคิอาโต้", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap คาปูชิโน__Cappuccino_ {
            get {
                object obj = ResourceManager.GetObject("คาปูชิโน (Cappuccino)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap คาปูชิโน__Cappuccino_1 {
            get {
                object obj = ResourceManager.GetObject("คาปูชิโน (Cappuccino)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap คาปูชิโน__Cappuccino_2 {
            get {
                object obj = ResourceManager.GetObject("คาปูชิโน (Cappuccino)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap คาปูชิโน__Cappuccino_3 {
            get {
                object obj = ResourceManager.GetObject("คาปูชิโน (Cappuccino)3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap คาปูชิโน__Cappuccino_4 {
            get {
                object obj = ResourceManager.GetObject("คาปูชิโน (Cappuccino)4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ช็อคโกแลต_Chocolate_ {
            get {
                object obj = ResourceManager.GetObject("ช็อคโกแลต(Chocolate)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ชา__Tea_ {
            get {
                object obj = ResourceManager.GetObject("ชา (Tea)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ชาเขียวนม__Green_Tea_With_Milk_ {
            get {
                object obj = ResourceManager.GetObject("ชาเขียวนม (Green Tea With Milk)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ชาเขียวน้ำผึ้งมะนาวเจลลี่__Green_Tea_Honey_Lime_With_Jelly_ {
            get {
                object obj = ResourceManager.GetObject("ชาเขียวน้ำผึ้งมะนาวเจลลี่ (Green Tea Honey Lime With Jelly)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ชาดำ__Black_Tea_ {
            get {
                object obj = ResourceManager.GetObject("ชาดำ (Black Tea)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ชานม__Tea_With_Milk_ {
            get {
                object obj = ResourceManager.GetObject("ชานม (Tea With Milk)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ชามะนาว__Lemon_Tea_ {
            get {
                object obj = ResourceManager.GetObject("ชามะนาว (Lemon Tea)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ดาร์คช็อกโกแลต__Dark_Chocolate_ {
            get {
                object obj = ResourceManager.GetObject("ดาร์คช็อกโกแลต (Dark Chocolate)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap นมสด_Fresh_Milk_ {
            get {
                object obj = ResourceManager.GetObject("นมสด(Fresh Milk)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap น้ำผลไม้ปั่น___มิกซ์เบอร์รี่_ {
            get {
                object obj = ResourceManager.GetObject("น้ำผลไม้ปั่น ( มิกซ์เบอร์รี่)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap น้ำผลไม้ปั่น__สตรอเบอร์รี่_ {
            get {
                object obj = ResourceManager.GetObject("น้ำผลไม้ปั่น (สตรอเบอร์รี่)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap น้ำผลไม้ปั่น_กี่วี่ปั่น {
            get {
                object obj = ResourceManager.GetObject("น้ำผลไม้ปั่น กี่วี่ปั่น", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap น้ำลิ้นจี่__Lychee_Juice_ {
            get {
                object obj = ResourceManager.GetObject("น้ำลิ้นจี่ (Lychee Juice)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap มอคค่า__Mocha_ {
            get {
                object obj = ResourceManager.GetObject("มอคค่า (Mocha)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap มัทฉะถั่วแดง {
            get {
                object obj = ResourceManager.GetObject("มัทฉะถั่วแดง", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap มัทฉะลาเต้__Matcha_Latte_ {
            get {
                object obj = ResourceManager.GetObject("มัทฉะลาเต้ (Matcha Latte)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap มัทฉะฮันนี่__Matcha_Honey_ {
            get {
                object obj = ResourceManager.GetObject("มัทฉะฮันนี่ (Matcha Honey)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ลาเต้อเมซอน__Latte_Amazon_ {
            get {
                object obj = ResourceManager.GetObject("ลาเต้อเมซอน (Latte Amazon)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap สตรอเบอร์รี่ชีสเค้ก__Strawberry_Cheesecake_ {
            get {
                object obj = ResourceManager.GetObject("สตรอเบอร์รี่ชีสเค้ก (Strawberry Cheesecake)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap อเมซอนเอ็กซ์ตร้า__Amazon_Extra_ {
            get {
                object obj = ResourceManager.GetObject("อเมซอนเอ็กซ์ตร้า (Amazon Extra)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
